version: "3.5"

services:
  nginx:
    container_name: c_nginx
    build: ./requirements/nginx/
    depend_on:
      - mariadb
      - wordpress
    volumes:
      - v_wp:/var/www/html
    ports:
      - 443:443
    networks:
      - inceptionnet
    restart : always

  wordpress:
    container_name: c_wordpress
    build:  
      context: ./requirements/wordpress/
      args:
        - DOMAIN_NAME=$DOMAIN_NAME
        - DB_NAME=$DB_NAME
        - DB_USER=$DB_USER
        - DB_USER_PASSWORD=$DB_USER_PASSWORD
        - WP_ADMIN=$WP_ADMIN
        - WP_ADMIN_PASSWORD=$WP_ADMIN_PASSWORD
        - WP_USER=$WP_USER
        - WP_USER_PASSWORD=$WP_USER_PASSWORD 
      env_file:
        - .env
      depend_on:
        - mariadb
      volumes:
        - v_wp:/var/www/html
      networks:
        - inceptionnet
      restart: always

  mariadb:
    container_name: c_mariadb 
    build: 
      context: ./requirements/mariadb/
      args:
        - DB_NAME=$DB_NAME
        - DB_ROOT_PASSWORD=$DB_ROOT_PASSWORD
        - DB_USER=$DB_USER
        - DB_USER_PASSWORD=$DB_USER_PASSWORD
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inceptionnet
    restart: always

volumes:
  v_wp:
    name: wordpress_volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/data/wordpress_volume
  v_db:
    name: mariadb_volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/data/mariadb_volume
  
networks:
  inceptionnet:
    name : inceptionnet
